version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "80:80"
  postgres:
    image: 'postgres'
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  users:
    build: ./users
    ports:
      - "50051:50051"
    depends_on: 
      - postgres
  posts:
    build: ./posts
    ports:
      - "50052:50052"
    depends_on: 
      - postgres
  comments:
    build: ./comments
    ports:
      - "50053:50053"
    depends_on: 
      - postgres
  likes:
    build: ./likes
    ports:
      - "50054:50054"
    depends_on: 
      - postgres
  hashtags:
    build: ./hashtag
    ports:
      - "50055:50055"
    depends_on: 
      - postgres
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on: 
      - users
      - posts
      - comments
      - likes
      - hashtags
    restart: always
    environment:
        USERS_ADDRESS: users:50051
        POSTS_ADDRESS: posts:50052
        COMMENTS_ADDRESS: comments:50053
        LIKES_ADDRESS: likes:50054
        USERS_HASHTAG: hashtag:50055
volumes: 
  data: