version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "80:80"
  postgres:
    image: 'postgres'
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  users:
    build: ./users
    restart: always
    ports:
      - "50051:50051"
    depends_on: 
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      POSTGRES_HOST: postgres
  posts:
    build: ./posts
    restart: always
    ports:
      - "50052:50052"
    depends_on: 
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      POSTGRES_HOST: postgres
  comments:
    build: ./comments
    ports:
      - "50053:50053"
    depends_on: 
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      POSTGRES_HOST: postgres
  likes:
    build: ./likes
    restart: always
    ports:
      - "50054:50054"
    depends_on: 
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      POSTGRES_HOST: postgres
  hashtags:
    build: ./hashtag
    restart: always
    ports:
      - "50055:50055"
    depends_on: 
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpcDB
      POSTGRES_HOST: postgres
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on: 
      - users
      - posts
      - comments
      - likes
      - hashtags
    restart: always
    environment:
        USERS_ADDRESS: users
        POSTS_ADDRESS: posts
        COMMENTS_ADDRESS: comments
        LIKES_ADDRESS: likes
        HASHTAGS_ADDRESS: hashtags
        FRONTEND: frontend:3000
        USERS_PORT: 50051
        POSTS_PORT: 50052
        COMMENTS_PORT: 50053
        LIKES_PORT: 50054
        HASHTAGS_PORT: 50055
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
        NEXT_PUBLIC_API_URL: localhost:8080
volumes: 
  data: