// Code generated by sqlc. DO NOT EDIT.

package pg

import ()

type Comment struct {
	Id        int32
	CreatedAt int64
	UpdatedAt int64
	Contents  string
	UserId    int32
	PostId    int32
}

type CommentLike struct {
	Id        int32
	CreatedAt int64
	UserId    int32
	CommentId int32
}

type Follower struct {
	Id         int32
	CreatedAt  int64
	LeaderId   int32
	FollowerId int32
}

type Hashtag struct {
	Id        int32
	CreatedAt int64
	Title     string
}

type HashtagPost struct {
	Id        int32
	HashtagId int32
	PostId    int32
}

type Post struct {
	Id        int32
	CreatedAt int64
	UpdatedAt int64
	Url       string
	Caption   string
	UserId    int32
}

type PostLike struct {
	Id        int32
	CreatedAt int64
	UserId    int32
	PostId    int32
}

type User struct {
	Id        int32
	CreatedAt int64
	UpdatedAt int64
	Username  string
	Bio       string
	Avatar    string
	Email     string
	Password  string
}
