apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: cesargdd/gateway-grpc
        env:
          - name: USERS_ADDRESS
            value: "users-service.default"
          - name: COMMENTS_ADDRESS
            value: "comments-service.default"
          - name: HASHTAGS_ADDRESS
            value: "hashtag-service.default"
          - name: LIKES_ADDRESS
            value: "likes-service.default"
          - name: POSTS_ADDRESS
            value: "posts-service.default"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
