// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: hashtagspb/hashtagspb.proto

package hashtagspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hashtag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Hashtag) Reset() {
	*x = Hashtag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hashtag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashtag) ProtoMessage() {}

func (x *Hashtag) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashtag.ProtoReflect.Descriptor instead.
func (*Hashtag) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{0}
}

func (x *Hashtag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hashtag) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Hashtag) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateHashtagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag *Hashtag `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *CreateHashtagRequest) Reset() {
	*x = CreateHashtagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashtagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashtagRequest) ProtoMessage() {}

func (x *CreateHashtagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashtagRequest.ProtoReflect.Descriptor instead.
func (*CreateHashtagRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHashtagRequest) GetHashtag() *Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type CreateHashtagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag *Hashtag `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *CreateHashtagResponse) Reset() {
	*x = CreateHashtagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashtagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashtagResponse) ProtoMessage() {}

func (x *CreateHashtagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashtagResponse.ProtoReflect.Descriptor instead.
func (*CreateHashtagResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHashtagResponse) GetHashtag() *Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type GetHashtagByTitleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GetHashtagByTitleRequest) Reset() {
	*x = GetHashtagByTitleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashtagByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagByTitleRequest) ProtoMessage() {}

func (x *GetHashtagByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagByTitleRequest.ProtoReflect.Descriptor instead.
func (*GetHashtagByTitleRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{3}
}

func (x *GetHashtagByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetHashtagByTitleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag *Hashtag `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *GetHashtagByTitleResponse) Reset() {
	*x = GetHashtagByTitleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashtagByTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagByTitleResponse) ProtoMessage() {}

func (x *GetHashtagByTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagByTitleResponse.ProtoReflect.Descriptor instead.
func (*GetHashtagByTitleResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{4}
}

func (x *GetHashtagByTitleResponse) GetHashtag() *Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type GetHashtagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHashtagRequest) Reset() {
	*x = GetHashtagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashtagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagRequest) ProtoMessage() {}

func (x *GetHashtagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagRequest.ProtoReflect.Descriptor instead.
func (*GetHashtagRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{5}
}

func (x *GetHashtagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHashtagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag *Hashtag `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *GetHashtagResponse) Reset() {
	*x = GetHashtagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashtagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagResponse) ProtoMessage() {}

func (x *GetHashtagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagResponse.ProtoReflect.Descriptor instead.
func (*GetHashtagResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{6}
}

func (x *GetHashtagResponse) GetHashtag() *Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type UpdateHashtagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *UpdateHashtagRequest) Reset() {
	*x = UpdateHashtagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHashtagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHashtagRequest) ProtoMessage() {}

func (x *UpdateHashtagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHashtagRequest.ProtoReflect.Descriptor instead.
func (*UpdateHashtagRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateHashtagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHashtagRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateHashtagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag *Hashtag `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *UpdateHashtagResponse) Reset() {
	*x = UpdateHashtagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHashtagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHashtagResponse) ProtoMessage() {}

func (x *UpdateHashtagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHashtagResponse.ProtoReflect.Descriptor instead.
func (*UpdateHashtagResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateHashtagResponse) GetHashtag() *Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type DeleteHashtagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHashtagRequest) Reset() {
	*x = DeleteHashtagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHashtagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHashtagRequest) ProtoMessage() {}

func (x *DeleteHashtagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHashtagRequest.ProtoReflect.Descriptor instead.
func (*DeleteHashtagRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteHashtagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteHashtagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag *Hashtag `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *DeleteHashtagResponse) Reset() {
	*x = DeleteHashtagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHashtagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHashtagResponse) ProtoMessage() {}

func (x *DeleteHashtagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHashtagResponse.ProtoReflect.Descriptor instead.
func (*DeleteHashtagResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHashtagResponse) GetHashtag() *Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type ListHashtagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHashtagsRequest) Reset() {
	*x = ListHashtagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagsRequest) ProtoMessage() {}

func (x *ListHashtagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagsRequest.ProtoReflect.Descriptor instead.
func (*ListHashtagsRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{11}
}

type ListHashtagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag []*Hashtag `protobuf:"bytes,1,rep,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *ListHashtagsResponse) Reset() {
	*x = ListHashtagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagsResponse) ProtoMessage() {}

func (x *ListHashtagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagsResponse.ProtoReflect.Descriptor instead.
func (*ListHashtagsResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{12}
}

func (x *ListHashtagsResponse) GetHashtag() []*Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type ListHashtagsByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListHashtagsByIdRequest) Reset() {
	*x = ListHashtagsByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagsByIdRequest) ProtoMessage() {}

func (x *ListHashtagsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagsByIdRequest.ProtoReflect.Descriptor instead.
func (*ListHashtagsByIdRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{13}
}

func (x *ListHashtagsByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListHashtagsByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashtag []*Hashtag `protobuf:"bytes,1,rep,name=hashtag,proto3" json:"hashtag,omitempty"`
}

func (x *ListHashtagsByIdResponse) Reset() {
	*x = ListHashtagsByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagsByIdResponse) ProtoMessage() {}

func (x *ListHashtagsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagsByIdResponse.ProtoReflect.Descriptor instead.
func (*ListHashtagsByIdResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{14}
}

func (x *ListHashtagsByIdResponse) GetHashtag() []*Hashtag {
	if x != nil {
		return x.Hashtag
	}
	return nil
}

type HashtagPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HashtagId int32 `protobuf:"varint,2,opt,name=hashtag_id,json=hashtagId,proto3" json:"hashtag_id,omitempty"`
	PostId    int32 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *HashtagPost) Reset() {
	*x = HashtagPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashtagPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashtagPost) ProtoMessage() {}

func (x *HashtagPost) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashtagPost.ProtoReflect.Descriptor instead.
func (*HashtagPost) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{15}
}

func (x *HashtagPost) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HashtagPost) GetHashtagId() int32 {
	if x != nil {
		return x.HashtagId
	}
	return 0
}

func (x *HashtagPost) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CreateHashtagPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashtagPost *HashtagPost `protobuf:"bytes,1,opt,name=hashtagPost,proto3" json:"hashtagPost,omitempty"`
}

func (x *CreateHashtagPostRequest) Reset() {
	*x = CreateHashtagPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashtagPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashtagPostRequest) ProtoMessage() {}

func (x *CreateHashtagPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashtagPostRequest.ProtoReflect.Descriptor instead.
func (*CreateHashtagPostRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{16}
}

func (x *CreateHashtagPostRequest) GetHashtagPost() *HashtagPost {
	if x != nil {
		return x.HashtagPost
	}
	return nil
}

type CreateHashtagPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashtagPost *HashtagPost `protobuf:"bytes,1,opt,name=hashtagPost,proto3" json:"hashtagPost,omitempty"`
}

func (x *CreateHashtagPostResponse) Reset() {
	*x = CreateHashtagPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashtagPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashtagPostResponse) ProtoMessage() {}

func (x *CreateHashtagPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashtagPostResponse.ProtoReflect.Descriptor instead.
func (*CreateHashtagPostResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{17}
}

func (x *CreateHashtagPostResponse) GetHashtagPost() *HashtagPost {
	if x != nil {
		return x.HashtagPost
	}
	return nil
}

type GetHashtagPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHashtagPostRequest) Reset() {
	*x = GetHashtagPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashtagPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagPostRequest) ProtoMessage() {}

func (x *GetHashtagPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagPostRequest.ProtoReflect.Descriptor instead.
func (*GetHashtagPostRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{18}
}

func (x *GetHashtagPostRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHashtagPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashtagPost *HashtagPost `protobuf:"bytes,1,opt,name=hashtagPost,proto3" json:"hashtagPost,omitempty"`
}

func (x *GetHashtagPostResponse) Reset() {
	*x = GetHashtagPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashtagPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagPostResponse) ProtoMessage() {}

func (x *GetHashtagPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagPostResponse.ProtoReflect.Descriptor instead.
func (*GetHashtagPostResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{19}
}

func (x *GetHashtagPostResponse) GetHashtagPost() *HashtagPost {
	if x != nil {
		return x.HashtagPost
	}
	return nil
}

type DeleteHashtagPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHashtagPostRequest) Reset() {
	*x = DeleteHashtagPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHashtagPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHashtagPostRequest) ProtoMessage() {}

func (x *DeleteHashtagPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHashtagPostRequest.ProtoReflect.Descriptor instead.
func (*DeleteHashtagPostRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteHashtagPostRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteHashtagPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashtagPost *HashtagPost `protobuf:"bytes,1,opt,name=hashtagPost,proto3" json:"hashtagPost,omitempty"`
}

func (x *DeleteHashtagPostResponse) Reset() {
	*x = DeleteHashtagPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHashtagPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHashtagPostResponse) ProtoMessage() {}

func (x *DeleteHashtagPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHashtagPostResponse.ProtoReflect.Descriptor instead.
func (*DeleteHashtagPostResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteHashtagPostResponse) GetHashtagPost() *HashtagPost {
	if x != nil {
		return x.HashtagPost
	}
	return nil
}

type ListHashtagPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHashtagPostsRequest) Reset() {
	*x = ListHashtagPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagPostsRequest) ProtoMessage() {}

func (x *ListHashtagPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagPostsRequest.ProtoReflect.Descriptor instead.
func (*ListHashtagPostsRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{22}
}

type ListHashtagPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashtagPost []*HashtagPost `protobuf:"bytes,1,rep,name=hashtagPost,proto3" json:"hashtagPost,omitempty"`
}

func (x *ListHashtagPostsResponse) Reset() {
	*x = ListHashtagPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagPostsResponse) ProtoMessage() {}

func (x *ListHashtagPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagPostsResponse.ProtoReflect.Descriptor instead.
func (*ListHashtagPostsResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{23}
}

func (x *ListHashtagPostsResponse) GetHashtagPost() []*HashtagPost {
	if x != nil {
		return x.HashtagPost
	}
	return nil
}

type ListHashtagPostsByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListHashtagPostsByIdRequest) Reset() {
	*x = ListHashtagPostsByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagPostsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagPostsByIdRequest) ProtoMessage() {}

func (x *ListHashtagPostsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagPostsByIdRequest.ProtoReflect.Descriptor instead.
func (*ListHashtagPostsByIdRequest) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{24}
}

func (x *ListHashtagPostsByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListHashtagPostsByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashtagPost []*HashtagPost `protobuf:"bytes,1,rep,name=hashtagPost,proto3" json:"hashtagPost,omitempty"`
}

func (x *ListHashtagPostsByIdResponse) Reset() {
	*x = ListHashtagPostsByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashtagspb_hashtagspb_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHashtagPostsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashtagPostsByIdResponse) ProtoMessage() {}

func (x *ListHashtagPostsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashtagspb_hashtagspb_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashtagPostsByIdResponse.ProtoReflect.Descriptor instead.
func (*ListHashtagPostsByIdResponse) Descriptor() ([]byte, []int) {
	return file_hashtagspb_hashtagspb_proto_rawDescGZIP(), []int{25}
}

func (x *ListHashtagPostsByIdResponse) GetHashtagPost() []*HashtagPost {
	if x != nil {
		return x.HashtagPost
	}
	return nil
}

var File_hashtagspb_hashtagspb_proto protoreflect.FileDescriptor

var file_hashtagspb_hashtagspb_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2f, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x22, 0x4e, 0x0a, 0x07, 0x48, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x22, 0x46, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52,
	0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x22, 0x30, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x42, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x4a, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x42, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x22, 0x3c, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x46,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x07, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x22, 0x29, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x49, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x52, 0x07, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x22, 0x55, 0x0a, 0x0b, 0x48, 0x61,
	0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x22, 0x55, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0b, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x2a,
	0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x19, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a,
	0x18, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x32, 0xf4,
	0x04, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x12, 0x20, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x42, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x24, 0x2e,
	0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x74, 0x61, 0x67, 0x42, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x42, 0x79, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x12, 0x1d, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x73, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x12, 0x20, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x12, 0x20,
	0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x12, 0x1f, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfc, 0x03, 0x0a, 0x13, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x24, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74,
	0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x57, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x21, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x24, 0x2e,
	0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x23,
	0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x27, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hashtagspb_hashtagspb_proto_rawDescOnce sync.Once
	file_hashtagspb_hashtagspb_proto_rawDescData = file_hashtagspb_hashtagspb_proto_rawDesc
)

func file_hashtagspb_hashtagspb_proto_rawDescGZIP() []byte {
	file_hashtagspb_hashtagspb_proto_rawDescOnce.Do(func() {
		file_hashtagspb_hashtagspb_proto_rawDescData = protoimpl.X.CompressGZIP(file_hashtagspb_hashtagspb_proto_rawDescData)
	})
	return file_hashtagspb_hashtagspb_proto_rawDescData
}

var file_hashtagspb_hashtagspb_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_hashtagspb_hashtagspb_proto_goTypes = []interface{}{
	(*Hashtag)(nil),                      // 0: hashtagspb.Hashtag
	(*CreateHashtagRequest)(nil),         // 1: hashtagspb.CreateHashtagRequest
	(*CreateHashtagResponse)(nil),        // 2: hashtagspb.CreateHashtagResponse
	(*GetHashtagByTitleRequest)(nil),     // 3: hashtagspb.GetHashtagByTitleRequest
	(*GetHashtagByTitleResponse)(nil),    // 4: hashtagspb.GetHashtagByTitleResponse
	(*GetHashtagRequest)(nil),            // 5: hashtagspb.GetHashtagRequest
	(*GetHashtagResponse)(nil),           // 6: hashtagspb.GetHashtagResponse
	(*UpdateHashtagRequest)(nil),         // 7: hashtagspb.UpdateHashtagRequest
	(*UpdateHashtagResponse)(nil),        // 8: hashtagspb.UpdateHashtagResponse
	(*DeleteHashtagRequest)(nil),         // 9: hashtagspb.DeleteHashtagRequest
	(*DeleteHashtagResponse)(nil),        // 10: hashtagspb.DeleteHashtagResponse
	(*ListHashtagsRequest)(nil),          // 11: hashtagspb.ListHashtagsRequest
	(*ListHashtagsResponse)(nil),         // 12: hashtagspb.ListHashtagsResponse
	(*ListHashtagsByIdRequest)(nil),      // 13: hashtagspb.ListHashtagsByIdRequest
	(*ListHashtagsByIdResponse)(nil),     // 14: hashtagspb.ListHashtagsByIdResponse
	(*HashtagPost)(nil),                  // 15: hashtagspb.HashtagPost
	(*CreateHashtagPostRequest)(nil),     // 16: hashtagspb.CreateHashtagPostRequest
	(*CreateHashtagPostResponse)(nil),    // 17: hashtagspb.CreateHashtagPostResponse
	(*GetHashtagPostRequest)(nil),        // 18: hashtagspb.GetHashtagPostRequest
	(*GetHashtagPostResponse)(nil),       // 19: hashtagspb.GetHashtagPostResponse
	(*DeleteHashtagPostRequest)(nil),     // 20: hashtagspb.DeleteHashtagPostRequest
	(*DeleteHashtagPostResponse)(nil),    // 21: hashtagspb.DeleteHashtagPostResponse
	(*ListHashtagPostsRequest)(nil),      // 22: hashtagspb.ListHashtagPostsRequest
	(*ListHashtagPostsResponse)(nil),     // 23: hashtagspb.ListHashtagPostsResponse
	(*ListHashtagPostsByIdRequest)(nil),  // 24: hashtagspb.ListHashtagPostsByIdRequest
	(*ListHashtagPostsByIdResponse)(nil), // 25: hashtagspb.ListHashtagPostsByIdResponse
}
var file_hashtagspb_hashtagspb_proto_depIdxs = []int32{
	0,  // 0: hashtagspb.CreateHashtagRequest.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 1: hashtagspb.CreateHashtagResponse.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 2: hashtagspb.GetHashtagByTitleResponse.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 3: hashtagspb.GetHashtagResponse.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 4: hashtagspb.UpdateHashtagResponse.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 5: hashtagspb.DeleteHashtagResponse.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 6: hashtagspb.ListHashtagsResponse.hashtag:type_name -> hashtagspb.Hashtag
	0,  // 7: hashtagspb.ListHashtagsByIdResponse.hashtag:type_name -> hashtagspb.Hashtag
	15, // 8: hashtagspb.CreateHashtagPostRequest.hashtagPost:type_name -> hashtagspb.HashtagPost
	15, // 9: hashtagspb.CreateHashtagPostResponse.hashtagPost:type_name -> hashtagspb.HashtagPost
	15, // 10: hashtagspb.GetHashtagPostResponse.hashtagPost:type_name -> hashtagspb.HashtagPost
	15, // 11: hashtagspb.DeleteHashtagPostResponse.hashtagPost:type_name -> hashtagspb.HashtagPost
	15, // 12: hashtagspb.ListHashtagPostsResponse.hashtagPost:type_name -> hashtagspb.HashtagPost
	15, // 13: hashtagspb.ListHashtagPostsByIdResponse.hashtagPost:type_name -> hashtagspb.HashtagPost
	1,  // 14: hashtagspb.HashtagsService.CreateHashtag:input_type -> hashtagspb.CreateHashtagRequest
	3,  // 15: hashtagspb.HashtagsService.GetHashtagByTitle:input_type -> hashtagspb.GetHashtagByTitleRequest
	5,  // 16: hashtagspb.HashtagsService.GetHashtag:input_type -> hashtagspb.GetHashtagRequest
	7,  // 17: hashtagspb.HashtagsService.UpdateHashtag:input_type -> hashtagspb.UpdateHashtagRequest
	9,  // 18: hashtagspb.HashtagsService.DeleteHashtag:input_type -> hashtagspb.DeleteHashtagRequest
	11, // 19: hashtagspb.HashtagsService.ListHashtags:input_type -> hashtagspb.ListHashtagsRequest
	13, // 20: hashtagspb.HashtagsService.ListHashtagsById:input_type -> hashtagspb.ListHashtagsByIdRequest
	16, // 21: hashtagspb.HashtagPostsService.CreateHashtagPost:input_type -> hashtagspb.CreateHashtagPostRequest
	18, // 22: hashtagspb.HashtagPostsService.GetHashtagPost:input_type -> hashtagspb.GetHashtagPostRequest
	20, // 23: hashtagspb.HashtagPostsService.DeleteHashtagPost:input_type -> hashtagspb.DeleteHashtagPostRequest
	22, // 24: hashtagspb.HashtagPostsService.ListHashtagPosts:input_type -> hashtagspb.ListHashtagPostsRequest
	24, // 25: hashtagspb.HashtagPostsService.ListHashtagPostsById:input_type -> hashtagspb.ListHashtagPostsByIdRequest
	2,  // 26: hashtagspb.HashtagsService.CreateHashtag:output_type -> hashtagspb.CreateHashtagResponse
	4,  // 27: hashtagspb.HashtagsService.GetHashtagByTitle:output_type -> hashtagspb.GetHashtagByTitleResponse
	6,  // 28: hashtagspb.HashtagsService.GetHashtag:output_type -> hashtagspb.GetHashtagResponse
	8,  // 29: hashtagspb.HashtagsService.UpdateHashtag:output_type -> hashtagspb.UpdateHashtagResponse
	10, // 30: hashtagspb.HashtagsService.DeleteHashtag:output_type -> hashtagspb.DeleteHashtagResponse
	12, // 31: hashtagspb.HashtagsService.ListHashtags:output_type -> hashtagspb.ListHashtagsResponse
	14, // 32: hashtagspb.HashtagsService.ListHashtagsById:output_type -> hashtagspb.ListHashtagsByIdResponse
	17, // 33: hashtagspb.HashtagPostsService.CreateHashtagPost:output_type -> hashtagspb.CreateHashtagPostResponse
	19, // 34: hashtagspb.HashtagPostsService.GetHashtagPost:output_type -> hashtagspb.GetHashtagPostResponse
	21, // 35: hashtagspb.HashtagPostsService.DeleteHashtagPost:output_type -> hashtagspb.DeleteHashtagPostResponse
	23, // 36: hashtagspb.HashtagPostsService.ListHashtagPosts:output_type -> hashtagspb.ListHashtagPostsResponse
	25, // 37: hashtagspb.HashtagPostsService.ListHashtagPostsById:output_type -> hashtagspb.ListHashtagPostsByIdResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_hashtagspb_hashtagspb_proto_init() }
func file_hashtagspb_hashtagspb_proto_init() {
	if File_hashtagspb_hashtagspb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hashtagspb_hashtagspb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hashtag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashtagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashtagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashtagByTitleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashtagByTitleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashtagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashtagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHashtagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHashtagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHashtagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHashtagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagsByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagsByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashtagPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashtagPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashtagPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashtagPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashtagPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHashtagPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHashtagPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagPostsByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashtagspb_hashtagspb_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHashtagPostsByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hashtagspb_hashtagspb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hashtagspb_hashtagspb_proto_goTypes,
		DependencyIndexes: file_hashtagspb_hashtagspb_proto_depIdxs,
		MessageInfos:      file_hashtagspb_hashtagspb_proto_msgTypes,
	}.Build()
	File_hashtagspb_hashtagspb_proto = out.File
	file_hashtagspb_hashtagspb_proto_rawDesc = nil
	file_hashtagspb_hashtagspb_proto_goTypes = nil
	file_hashtagspb_hashtagspb_proto_depIdxs = nil
}
