// Code generated by sqlc. DO NOT EDIT.

package pg

import ()

type Hashtag struct {
	Id        int32
	CreatedAt int64
	Title     string
}

type HashtagPost struct {
	Id        int32
	HashtagId int32
	PostId    int32
}
