// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pb/pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostLike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId    int32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId    int32 `protobuf:"varint,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *PostLike) Reset() {
	*x = PostLike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLike) ProtoMessage() {}

func (x *PostLike) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLike.ProtoReflect.Descriptor instead.
func (*PostLike) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{0}
}

func (x *PostLike) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostLike) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostLike) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostLike) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CreatePostLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike *PostLike `protobuf:"bytes,1,opt,name=postLike,proto3" json:"postLike,omitempty"`
}

func (x *CreatePostLikeRequest) Reset() {
	*x = CreatePostLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeRequest) ProtoMessage() {}

func (x *CreatePostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeRequest.ProtoReflect.Descriptor instead.
func (*CreatePostLikeRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostLikeRequest) GetPostLike() *PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type CreatePostLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike *PostLike `protobuf:"bytes,1,opt,name=postLike,proto3" json:"postLike,omitempty"`
}

func (x *CreatePostLikeResponse) Reset() {
	*x = CreatePostLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeResponse) ProtoMessage() {}

func (x *CreatePostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeResponse.ProtoReflect.Descriptor instead.
func (*CreatePostLikeResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostLikeResponse) GetPostLike() *PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type GetPostLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPostLikeRequest) Reset() {
	*x = GetPostLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikeRequest) ProtoMessage() {}

func (x *GetPostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikeRequest.ProtoReflect.Descriptor instead.
func (*GetPostLikeRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{3}
}

func (x *GetPostLikeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPostLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike *PostLike `protobuf:"bytes,1,opt,name=postLike,proto3" json:"postLike,omitempty"`
}

func (x *GetPostLikeResponse) Reset() {
	*x = GetPostLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikeResponse) ProtoMessage() {}

func (x *GetPostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikeResponse.ProtoReflect.Descriptor instead.
func (*GetPostLikeResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostLikeResponse) GetPostLike() *PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type DeletePostLikeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePostLikeByIdRequest) Reset() {
	*x = DeletePostLikeByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostLikeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeByIdRequest) ProtoMessage() {}

func (x *DeletePostLikeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeByIdRequest.ProtoReflect.Descriptor instead.
func (*DeletePostLikeByIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePostLikeByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePostLikeByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike *PostLike `protobuf:"bytes,1,opt,name=PostLike,proto3" json:"PostLike,omitempty"`
}

func (x *DeletePostLikeByIdResponse) Reset() {
	*x = DeletePostLikeByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostLikeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeByIdResponse) ProtoMessage() {}

func (x *DeletePostLikeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeByIdResponse.ProtoReflect.Descriptor instead.
func (*DeletePostLikeByIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePostLikeByIdResponse) GetPostLike() *PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type DeletePostLikeByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePostLikeByUserIdRequest) Reset() {
	*x = DeletePostLikeByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostLikeByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeByUserIdRequest) ProtoMessage() {}

func (x *DeletePostLikeByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeByUserIdRequest.ProtoReflect.Descriptor instead.
func (*DeletePostLikeByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostLikeByUserIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePostLikeByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike *PostLike `protobuf:"bytes,1,opt,name=PostLike,proto3" json:"PostLike,omitempty"`
}

func (x *DeletePostLikeByUserIdResponse) Reset() {
	*x = DeletePostLikeByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostLikeByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeByUserIdResponse) ProtoMessage() {}

func (x *DeletePostLikeByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeByUserIdResponse.ProtoReflect.Descriptor instead.
func (*DeletePostLikeByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostLikeByUserIdResponse) GetPostLike() *PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type ListPostLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPostLikesRequest) Reset() {
	*x = ListPostLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostLikesRequest) ProtoMessage() {}

func (x *ListPostLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostLikesRequest.ProtoReflect.Descriptor instead.
func (*ListPostLikesRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{9}
}

type ListPostLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike []*PostLike `protobuf:"bytes,1,rep,name=PostLike,proto3" json:"PostLike,omitempty"`
}

func (x *ListPostLikesResponse) Reset() {
	*x = ListPostLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostLikesResponse) ProtoMessage() {}

func (x *ListPostLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostLikesResponse.ProtoReflect.Descriptor instead.
func (*ListPostLikesResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{10}
}

func (x *ListPostLikesResponse) GetPostLike() []*PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type ListPostLikesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListPostLikesByIdRequest) Reset() {
	*x = ListPostLikesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostLikesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostLikesByIdRequest) ProtoMessage() {}

func (x *ListPostLikesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostLikesByIdRequest.ProtoReflect.Descriptor instead.
func (*ListPostLikesByIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{11}
}

func (x *ListPostLikesByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPostLikesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike []*PostLike `protobuf:"bytes,1,rep,name=PostLike,proto3" json:"PostLike,omitempty"`
}

func (x *ListPostLikesByIdResponse) Reset() {
	*x = ListPostLikesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostLikesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostLikesByIdResponse) ProtoMessage() {}

func (x *ListPostLikesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostLikesByIdResponse.ProtoReflect.Descriptor instead.
func (*ListPostLikesByIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{12}
}

func (x *ListPostLikesByIdResponse) GetPostLike() []*PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type ListPostLikesByPostIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int32 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *ListPostLikesByPostIdRequest) Reset() {
	*x = ListPostLikesByPostIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostLikesByPostIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostLikesByPostIdRequest) ProtoMessage() {}

func (x *ListPostLikesByPostIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostLikesByPostIdRequest.ProtoReflect.Descriptor instead.
func (*ListPostLikesByPostIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostLikesByPostIdRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type ListPostLikesByPostIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostLike []*PostLike `protobuf:"bytes,1,rep,name=PostLike,proto3" json:"PostLike,omitempty"`
}

func (x *ListPostLikesByPostIdResponse) Reset() {
	*x = ListPostLikesByPostIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostLikesByPostIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostLikesByPostIdResponse) ProtoMessage() {}

func (x *ListPostLikesByPostIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostLikesByPostIdResponse.ProtoReflect.Descriptor instead.
func (*ListPostLikesByPostIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{14}
}

func (x *ListPostLikesByPostIdResponse) GetPostLike() []*PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

type CommentLike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId    int32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId int32 `protobuf:"varint,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
}

func (x *CommentLike) Reset() {
	*x = CommentLike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentLike) ProtoMessage() {}

func (x *CommentLike) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentLike.ProtoReflect.Descriptor instead.
func (*CommentLike) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{15}
}

func (x *CommentLike) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentLike) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentLike) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentLike) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type CreateCommentLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike *CommentLike `protobuf:"bytes,1,opt,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *CreateCommentLikeRequest) Reset() {
	*x = CreateCommentLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentLikeRequest) ProtoMessage() {}

func (x *CreateCommentLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentLikeRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentLikeRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentLikeRequest) GetCommentLike() *CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type CreateCommentLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike *CommentLike `protobuf:"bytes,1,opt,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *CreateCommentLikeResponse) Reset() {
	*x = CreateCommentLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentLikeResponse) ProtoMessage() {}

func (x *CreateCommentLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentLikeResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentLikeResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCommentLikeResponse) GetCommentLike() *CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type GetCommentLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCommentLikeRequest) Reset() {
	*x = GetCommentLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentLikeRequest) ProtoMessage() {}

func (x *GetCommentLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentLikeRequest.ProtoReflect.Descriptor instead.
func (*GetCommentLikeRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{18}
}

func (x *GetCommentLikeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCommentLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike *CommentLike `protobuf:"bytes,1,opt,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *GetCommentLikeResponse) Reset() {
	*x = GetCommentLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentLikeResponse) ProtoMessage() {}

func (x *GetCommentLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentLikeResponse.ProtoReflect.Descriptor instead.
func (*GetCommentLikeResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{19}
}

func (x *GetCommentLikeResponse) GetCommentLike() *CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type DeleteCommentLikeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCommentLikeByIdRequest) Reset() {
	*x = DeleteCommentLikeByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentLikeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentLikeByIdRequest) ProtoMessage() {}

func (x *DeleteCommentLikeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentLikeByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentLikeByIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCommentLikeByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCommentLikeByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike *CommentLike `protobuf:"bytes,1,opt,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *DeleteCommentLikeByIdResponse) Reset() {
	*x = DeleteCommentLikeByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentLikeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentLikeByIdResponse) ProtoMessage() {}

func (x *DeleteCommentLikeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentLikeByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentLikeByIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCommentLikeByIdResponse) GetCommentLike() *CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type DeleteCommentLikeByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCommentLikeByUserIdRequest) Reset() {
	*x = DeleteCommentLikeByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentLikeByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentLikeByUserIdRequest) ProtoMessage() {}

func (x *DeleteCommentLikeByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentLikeByUserIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentLikeByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCommentLikeByUserIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCommentLikeByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike *CommentLike `protobuf:"bytes,1,opt,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *DeleteCommentLikeByUserIdResponse) Reset() {
	*x = DeleteCommentLikeByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentLikeByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentLikeByUserIdResponse) ProtoMessage() {}

func (x *DeleteCommentLikeByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentLikeByUserIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentLikeByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCommentLikeByUserIdResponse) GetCommentLike() *CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type ListCommentLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCommentLikesRequest) Reset() {
	*x = ListCommentLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentLikesRequest) ProtoMessage() {}

func (x *ListCommentLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentLikesRequest.ProtoReflect.Descriptor instead.
func (*ListCommentLikesRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{24}
}

type ListCommentLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike []*CommentLike `protobuf:"bytes,1,rep,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *ListCommentLikesResponse) Reset() {
	*x = ListCommentLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentLikesResponse) ProtoMessage() {}

func (x *ListCommentLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentLikesResponse.ProtoReflect.Descriptor instead.
func (*ListCommentLikesResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{25}
}

func (x *ListCommentLikesResponse) GetCommentLike() []*CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type ListCommentLikesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListCommentLikesByIdRequest) Reset() {
	*x = ListCommentLikesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentLikesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentLikesByIdRequest) ProtoMessage() {}

func (x *ListCommentLikesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentLikesByIdRequest.ProtoReflect.Descriptor instead.
func (*ListCommentLikesByIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{26}
}

func (x *ListCommentLikesByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCommentLikesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike []*CommentLike `protobuf:"bytes,1,rep,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *ListCommentLikesByIdResponse) Reset() {
	*x = ListCommentLikesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentLikesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentLikesByIdResponse) ProtoMessage() {}

func (x *ListCommentLikesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentLikesByIdResponse.ProtoReflect.Descriptor instead.
func (*ListCommentLikesByIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{27}
}

func (x *ListCommentLikesByIdResponse) GetCommentLike() []*CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

type ListCommentLikesByCommentIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId int32 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
}

func (x *ListCommentLikesByCommentIdRequest) Reset() {
	*x = ListCommentLikesByCommentIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentLikesByCommentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentLikesByCommentIdRequest) ProtoMessage() {}

func (x *ListCommentLikesByCommentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentLikesByCommentIdRequest.ProtoReflect.Descriptor instead.
func (*ListCommentLikesByCommentIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{28}
}

func (x *ListCommentLikesByCommentIdRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type ListCommentLikesByCommentIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentLike []*CommentLike `protobuf:"bytes,1,rep,name=commentLike,proto3" json:"commentLike,omitempty"`
}

func (x *ListCommentLikesByCommentIdResponse) Reset() {
	*x = ListCommentLikesByCommentIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pb_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentLikesByCommentIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentLikesByCommentIdResponse) ProtoMessage() {}

func (x *ListCommentLikesByCommentIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pb_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentLikesByCommentIdResponse.ProtoReflect.Descriptor instead.
func (*ListCommentLikesByCommentIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_pb_proto_rawDescGZIP(), []int{29}
}

func (x *ListCommentLikesByCommentIdResponse) GetCommentLike() []*CommentLike {
	if x != nil {
		return x.CommentLike
	}
	return nil
}

var File_pb_pb_proto protoreflect.FileDescriptor

var file_pb_pb_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x6b, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x41,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x22, 0x42, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x2b, 0x0a, 0x19,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x1a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x22, 0x2f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x4a, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x16,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52,
	0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x37, 0x0a, 0x1c,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x22, 0x74, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x4e, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4b,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x2e, 0x0a, 0x1c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x1d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22,
	0x32, 0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x43, 0x0a, 0x22, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x23,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x42, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x32, 0xc7, 0x04, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x19, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5c, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x92, 0x05, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x20, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x68, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12,
	0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_pb_proto_rawDescOnce sync.Once
	file_pb_pb_proto_rawDescData = file_pb_pb_proto_rawDesc
)

func file_pb_pb_proto_rawDescGZIP() []byte {
	file_pb_pb_proto_rawDescOnce.Do(func() {
		file_pb_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_pb_proto_rawDescData)
	})
	return file_pb_pb_proto_rawDescData
}

var file_pb_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_pb_pb_proto_goTypes = []interface{}{
	(*PostLike)(nil),                            // 0: pb.PostLike
	(*CreatePostLikeRequest)(nil),               // 1: pb.CreatePostLikeRequest
	(*CreatePostLikeResponse)(nil),              // 2: pb.CreatePostLikeResponse
	(*GetPostLikeRequest)(nil),                  // 3: pb.GetPostLikeRequest
	(*GetPostLikeResponse)(nil),                 // 4: pb.GetPostLikeResponse
	(*DeletePostLikeByIdRequest)(nil),           // 5: pb.DeletePostLikeByIdRequest
	(*DeletePostLikeByIdResponse)(nil),          // 6: pb.DeletePostLikeByIdResponse
	(*DeletePostLikeByUserIdRequest)(nil),       // 7: pb.DeletePostLikeByUserIdRequest
	(*DeletePostLikeByUserIdResponse)(nil),      // 8: pb.DeletePostLikeByUserIdResponse
	(*ListPostLikesRequest)(nil),                // 9: pb.ListPostLikesRequest
	(*ListPostLikesResponse)(nil),               // 10: pb.ListPostLikesResponse
	(*ListPostLikesByIdRequest)(nil),            // 11: pb.ListPostLikesByIdRequest
	(*ListPostLikesByIdResponse)(nil),           // 12: pb.ListPostLikesByIdResponse
	(*ListPostLikesByPostIdRequest)(nil),        // 13: pb.ListPostLikesByPostIdRequest
	(*ListPostLikesByPostIdResponse)(nil),       // 14: pb.ListPostLikesByPostIdResponse
	(*CommentLike)(nil),                         // 15: pb.CommentLike
	(*CreateCommentLikeRequest)(nil),            // 16: pb.CreateCommentLikeRequest
	(*CreateCommentLikeResponse)(nil),           // 17: pb.CreateCommentLikeResponse
	(*GetCommentLikeRequest)(nil),               // 18: pb.GetCommentLikeRequest
	(*GetCommentLikeResponse)(nil),              // 19: pb.GetCommentLikeResponse
	(*DeleteCommentLikeByIdRequest)(nil),        // 20: pb.DeleteCommentLikeByIdRequest
	(*DeleteCommentLikeByIdResponse)(nil),       // 21: pb.DeleteCommentLikeByIdResponse
	(*DeleteCommentLikeByUserIdRequest)(nil),    // 22: pb.DeleteCommentLikeByUserIdRequest
	(*DeleteCommentLikeByUserIdResponse)(nil),   // 23: pb.DeleteCommentLikeByUserIdResponse
	(*ListCommentLikesRequest)(nil),             // 24: pb.ListCommentLikesRequest
	(*ListCommentLikesResponse)(nil),            // 25: pb.ListCommentLikesResponse
	(*ListCommentLikesByIdRequest)(nil),         // 26: pb.ListCommentLikesByIdRequest
	(*ListCommentLikesByIdResponse)(nil),        // 27: pb.ListCommentLikesByIdResponse
	(*ListCommentLikesByCommentIdRequest)(nil),  // 28: pb.ListCommentLikesByCommentIdRequest
	(*ListCommentLikesByCommentIdResponse)(nil), // 29: pb.ListCommentLikesByCommentIdResponse
}
var file_pb_pb_proto_depIdxs = []int32{
	0,  // 0: pb.CreatePostLikeRequest.postLike:type_name -> pb.PostLike
	0,  // 1: pb.CreatePostLikeResponse.postLike:type_name -> pb.PostLike
	0,  // 2: pb.GetPostLikeResponse.postLike:type_name -> pb.PostLike
	0,  // 3: pb.DeletePostLikeByIdResponse.PostLike:type_name -> pb.PostLike
	0,  // 4: pb.DeletePostLikeByUserIdResponse.PostLike:type_name -> pb.PostLike
	0,  // 5: pb.ListPostLikesResponse.PostLike:type_name -> pb.PostLike
	0,  // 6: pb.ListPostLikesByIdResponse.PostLike:type_name -> pb.PostLike
	0,  // 7: pb.ListPostLikesByPostIdResponse.PostLike:type_name -> pb.PostLike
	15, // 8: pb.CreateCommentLikeRequest.commentLike:type_name -> pb.CommentLike
	15, // 9: pb.CreateCommentLikeResponse.commentLike:type_name -> pb.CommentLike
	15, // 10: pb.GetCommentLikeResponse.commentLike:type_name -> pb.CommentLike
	15, // 11: pb.DeleteCommentLikeByIdResponse.commentLike:type_name -> pb.CommentLike
	15, // 12: pb.DeleteCommentLikeByUserIdResponse.commentLike:type_name -> pb.CommentLike
	15, // 13: pb.ListCommentLikesResponse.commentLike:type_name -> pb.CommentLike
	15, // 14: pb.ListCommentLikesByIdResponse.commentLike:type_name -> pb.CommentLike
	15, // 15: pb.ListCommentLikesByCommentIdResponse.commentLike:type_name -> pb.CommentLike
	1,  // 16: pb.PostLikesService.CreatePostLike:input_type -> pb.CreatePostLikeRequest
	3,  // 17: pb.PostLikesService.GetPostLike:input_type -> pb.GetPostLikeRequest
	5,  // 18: pb.PostLikesService.DeletePostLikeById:input_type -> pb.DeletePostLikeByIdRequest
	7,  // 19: pb.PostLikesService.DeletePostLikeByUserId:input_type -> pb.DeletePostLikeByUserIdRequest
	9,  // 20: pb.PostLikesService.ListPostLikes:input_type -> pb.ListPostLikesRequest
	11, // 21: pb.PostLikesService.ListPostLikesById:input_type -> pb.ListPostLikesByIdRequest
	13, // 22: pb.PostLikesService.ListPostLikesByPostId:input_type -> pb.ListPostLikesByPostIdRequest
	16, // 23: pb.CommentLikesService.CreateCommentLike:input_type -> pb.CreateCommentLikeRequest
	18, // 24: pb.CommentLikesService.GetCommentLike:input_type -> pb.GetCommentLikeRequest
	20, // 25: pb.CommentLikesService.DeleteCommentLikeById:input_type -> pb.DeleteCommentLikeByIdRequest
	22, // 26: pb.CommentLikesService.DeleteCommentLikeByUserId:input_type -> pb.DeleteCommentLikeByUserIdRequest
	24, // 27: pb.CommentLikesService.ListCommentLikes:input_type -> pb.ListCommentLikesRequest
	26, // 28: pb.CommentLikesService.ListCommentLikesById:input_type -> pb.ListCommentLikesByIdRequest
	28, // 29: pb.CommentLikesService.ListCommentLikesByCommentId:input_type -> pb.ListCommentLikesByCommentIdRequest
	2,  // 30: pb.PostLikesService.CreatePostLike:output_type -> pb.CreatePostLikeResponse
	4,  // 31: pb.PostLikesService.GetPostLike:output_type -> pb.GetPostLikeResponse
	6,  // 32: pb.PostLikesService.DeletePostLikeById:output_type -> pb.DeletePostLikeByIdResponse
	8,  // 33: pb.PostLikesService.DeletePostLikeByUserId:output_type -> pb.DeletePostLikeByUserIdResponse
	10, // 34: pb.PostLikesService.ListPostLikes:output_type -> pb.ListPostLikesResponse
	12, // 35: pb.PostLikesService.ListPostLikesById:output_type -> pb.ListPostLikesByIdResponse
	14, // 36: pb.PostLikesService.ListPostLikesByPostId:output_type -> pb.ListPostLikesByPostIdResponse
	17, // 37: pb.CommentLikesService.CreateCommentLike:output_type -> pb.CreateCommentLikeResponse
	19, // 38: pb.CommentLikesService.GetCommentLike:output_type -> pb.GetCommentLikeResponse
	21, // 39: pb.CommentLikesService.DeleteCommentLikeById:output_type -> pb.DeleteCommentLikeByIdResponse
	23, // 40: pb.CommentLikesService.DeleteCommentLikeByUserId:output_type -> pb.DeleteCommentLikeByUserIdResponse
	25, // 41: pb.CommentLikesService.ListCommentLikes:output_type -> pb.ListCommentLikesResponse
	27, // 42: pb.CommentLikesService.ListCommentLikesById:output_type -> pb.ListCommentLikesByIdResponse
	29, // 43: pb.CommentLikesService.ListCommentLikesByCommentId:output_type -> pb.ListCommentLikesByCommentIdResponse
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pb_pb_proto_init() }
func file_pb_pb_proto_init() {
	if File_pb_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostLike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostLikeByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostLikeByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostLikeByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostLikeByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostLikesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostLikesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostLikesByPostIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostLikesByPostIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentLike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentLikeByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentLikeByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentLikeByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentLikeByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentLikesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentLikesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentLikesByCommentIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pb_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentLikesByCommentIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_pb_proto_goTypes,
		DependencyIndexes: file_pb_pb_proto_depIdxs,
		MessageInfos:      file_pb_pb_proto_msgTypes,
	}.Build()
	File_pb_pb_proto = out.File
	file_pb_pb_proto_rawDesc = nil
	file_pb_pb_proto_goTypes = nil
	file_pb_pb_proto_depIdxs = nil
}
