// Code generated by sqlc. DO NOT EDIT.

package pg

import ()

type CommentLike struct {
	Id        int32
	CreatedAt int64
	UserId    int32
	CommentId int32
}

type PostLike struct {
	Id        int32
	CreatedAt int64
	UserId    int32
	PostId    int32
}
